### ISSUE TITLE
zeta check is not working properly

### ISSUE THREAD

**Issue by rodrigopex** [zeta-middleware/zeta#118]
When checking some project the include the _zeta.cmake_ without the CMAKE_CURRENT_DIR in front, the check says the file was not included at the CMakeLists.txt. Is it a minor issue.

**Comment by lucaspeixotot** [comment]
There is no bug about that. Actually the zeta check just check as OK when the include the zeta.cmake is written without CMAKE_CURRENT_DIR, more precisely when in CmakeLists the zeta.cmake is included as _include(zeta.cmake NO_POLICY_SCOPE)_.

The problem with samples that are reporting FAIL in zeta check is because the include was written as _include(zeta.cmake NO_POLICE_SCOPE)_.

As the bug there isn't I will close the issue, but we can discuss about use regex to accept the include the zeta.cmake with CMAKE_CURRENT_DIR and without it.
